version: 0.2 
phases: 
  pre_build: 
    commands: 
    - echo docker info                          
    - docker info 
      
    - echo Logging in to Amazon ECR.... 
    - aws --version
    
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 985509296439.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    
    - echo ECR login successful... 
  build: 
    commands: 
    - echo Build started on `date`
    
    - mvn clean package -Ddockerfile.skip
    - echo docker image build Successfully..
    
    - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
    - IMAGE_URI=$REPOSITORY_URI:$TAG
    
    - echo $TAG
    - echo $IMAGE_URI
    
    - echo image tagging started...
    
    - TAG_URI=985509296439.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_URI
    - echo $TAG_URI
    
    - docker build --tag $IMAGE_URI $TAG_URI 
    
    - echo image Successfully tagged.
    
    
  post_build: 
    commands: 
    - printenv
    - echo Build completed on `date`
    - echo Pushing docker image
    
    - docker push $TAG_URI
    
    - echo push completed
    - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $TAG_URI > imagedefinitions.json
artifacts:
  files:
  - imagedefinitions.json